In [1]:
import pandas as pd

# ESG data USA

In [2]:
#SPDR S&P 500 ESG ETF (EFIV) USA
USA_data = pd.read_csv(r"file")

print(USA_data)

    Identifier          Company Name     ISIN Code Ticker Symbol  \
0          NaN                   NaN           NaN           NaN
1          NaN                   NaN           NaN           NaN
2    537910017                   NaN           NaN           NaN
3      .ONEUSD                   NaN           NaN           NaN
4        AFL.N             Aflac Inc  US0010551028           AFL
..         ...                   ...           ...           ...
314     CTVA.N           Corteva Inc  US22052L1044          CTVA
315     AMCR.N             Amcor PLC  JE00BJ1F3079          AMCR
316     CARR.N   Carrier Global Corp  US14448C1045          CARR
317     OTIS.N   Otis Worldwide Corp  US68902V1070          OTIS
318       SW.N  Smurfit WestRock PLC  IE00028FXN24            SW

          Country of Exchange  \
0                         NaN
1                         NaN
2                         NaN
3                         NaN
4    United States of America
..                        ...
314  United States of America
315  United States of America
316  United States of America
317  United States of America
318  United States of America

                          NAICS National Industry Name  Size\n(:)  \
0                                                  NaN        NaN
1                                                  NaN        NaN
2                                                  NaN        NaN
3                                                  NaN        NaN
4         Direct Health and Medical Insurance Carriers        NaN
..                                                 ...        ...
314                 Farm Supplies Merchant Wholesalers        NaN
315  Plastics Packaging Film and Sheet (including L...        NaN
316  Air-Conditioning and Warm Air Heating Equipmen...        NaN
317         Elevator and Moving Stairway Manufacturing        NaN
318                All Other Business Support Services        NaN

    ESG Score\nIn the last 25 FY  Unnamed: 8  Unnamed: 9  ... Unnamed: 1622  \
0      (Date)\nIn the last 25 FY         NaN         NaN  ...           NaN
1                            FY0        FY-1        FY-2  ...         FY-15
2                            NaN         NaN         NaN  ...           NaN
3                            NaN         NaN         NaN  ...           NaN
4                     31/12/2023  31/12/2022  31/12/2021  ...  1,211,600.00
..                           ...         ...         ...  ...           ...
314                   31/12/2023  31/12/2022  31/12/2021  ...          0.00
315                   30/06/2024  30/06/2023  30/06/2022  ...          0.00
316                   31/12/2022  31/12/2021  31/12/2020  ...          0.00
317                   31/12/2023  31/12/2022  31/12/2021  ...          0.00
318                   31/12/2022  31/12/2021  31/12/2020  ...          0.00

    Unnamed: 1623 Unnamed: 1624 Unnamed: 1625 Unnamed: 1626 Unnamed: 1627  \
0             NaN           NaN           NaN           NaN           NaN
1           FY-16         FY-17         FY-18         FY-19         FY-20
2             NaN           NaN           NaN           NaN           NaN
3             NaN           NaN           NaN           NaN           NaN
4    2,132,000.00  1,436,000.00          0.00          0.00  1,176,000.00
..            ...           ...           ...           ...           ...
314          0.00          0.00          0.00          0.00          0.00
315          0.00          0.00          0.00          0.00          0.00
316          0.00          0.00          0.00          0.00          0.00
317          0.00          0.00          0.00          0.00          0.00
318          0.00          0.00          0.00          0.00          0.00

    Unnamed: 1628 Unnamed: 1629 Unnamed: 1630 Unnamed: 1631
0             NaN           NaN           NaN           NaN
1           FY-21         FY-22         FY-23         FY-24
2             NaN           NaN           NaN           NaN
3             NaN           NaN           NaN           NaN
4    2,067,800.00  2,255,800.00  3,150,800.00          0.00
..            ...           ...           ...           ...
314          0.00          0.00          0.00          0.00
315          0.00          0.00          0.00          0.00
316          0.00          0.00          0.00          0.00
317          0.00          0.00          0.00          0.00
318          0.00          0.00          0.00          0.00

[319 rows x 1632 columns]

In [9]:
print(USA_data.iloc[:, 30:55].dtypes)  # ESG score columns

Unnamed: 30    object
Unnamed: 31    object
Unnamed: 32    object
Unnamed: 33    object
Unnamed: 34    object
Unnamed: 35    object
Unnamed: 36    object
Unnamed: 37    object
Unnamed: 38    object
Unnamed: 39    object
Unnamed: 40    object
Unnamed: 41    object
Unnamed: 42    object
Unnamed: 43    object
Unnamed: 44    object
Unnamed: 45    object
Unnamed: 46    object
Unnamed: 47    object
Unnamed: 48    object
Unnamed: 49    object
Unnamed: 50    object
Unnamed: 51    object
Unnamed: 52    object
Unnamed: 53    object
Unnamed: 54    object
dtype: object

In [5]:
USA_data = USA_data.drop(columns=['Size\n(:)'])

print(USA_data.head(10))

  Identifier                    Company Name     ISIN Code Ticker Symbol  \
0        NaN                             NaN           NaN           NaN
1        NaN                             NaN           NaN           NaN
2  537910017                             NaN           NaN           NaN
3    .ONEUSD                             NaN           NaN           NaN
4      AFL.N                       Aflac Inc  US0010551028           AFL
5      ABT.N             Abbott Laboratories  US0028241000           ABT
6    ADBE.OQ                       Adobe Inc  US00724F1012          ADBE
7     AMD.OQ      Advanced Micro Devices Inc  US0079031078           AMD
8      APD.N  Air Products and Chemicals Inc  US0091581068           APD
9      ALB.N                  Albemarle Corp  US0126531013           ALB

        Country of Exchange  \
0                       NaN
1                       NaN
2                       NaN
3                       NaN
4  United States of America
5  United States of America
6  United States of America
7  United States of America
8  United States of America
9  United States of America

                        NAICS National Industry Name  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4       Direct Health and Medical Insurance Carriers
5  Electromedical and Electrotherapeutic Apparatu...
6                                Software Publishers
7     Semiconductor and Related Device Manufacturing
8                       Industrial Gas Manufacturing
9       Other Basic Inorganic Chemical Manufacturing

  ESG Score\nIn the last 25 FY  Unnamed: 8  Unnamed: 9 Unnamed: 10  ...  \
0    (Date)\nIn the last 25 FY         NaN         NaN         NaN  ...
1                          FY0        FY-1        FY-2        FY-3  ...
2                          NaN         NaN         NaN         NaN  ...
3                          NaN         NaN         NaN         NaN  ...
4                   31/12/2023  31/12/2022  31/12/2021  31/12/2020  ...
5                   31/12/2023  31/12/2022  31/12/2021  31/12/2020  ...
6                   01/12/2023  02/12/2022  03/12/2021  27/11/2020  ...
7                   30/12/2023  31/12/2022  25/12/2021  26/12/2020  ...
8                   30/09/2023  30/09/2022  30/09/2021  30/09/2020  ...
9                   31/12/2023  31/12/2022  31/12/2021  31/12/2020  ...

  Unnamed: 1622 Unnamed: 1623 Unnamed: 1624 Unnamed: 1625 Unnamed: 1626  \
0           NaN           NaN           NaN           NaN           NaN
1         FY-15         FY-16         FY-17         FY-18         FY-19
2           NaN           NaN           NaN           NaN           NaN
3           NaN           NaN           NaN           NaN           NaN
4  1,211,600.00  2,132,000.00  1,436,000.00          0.00          0.00
5  1,408,500.00  1,644,600.00  2,511,500.00          0.00          0.00
6    885,600.00  1,916,445.00  1,829,932.00          0.00          0.00
7  1,390,100.00  2,939,100.00  5,420,900.00          0.00          0.00
8    184,900.00    709,600.00    628,800.00          0.00          0.00
9    153,100.00    417,900.00    265,300.00          0.00          0.00

  Unnamed: 1627 Unnamed: 1628 Unnamed: 1629 Unnamed: 1630 Unnamed: 1631
0           NaN           NaN           NaN           NaN           NaN
1         FY-20         FY-21         FY-22         FY-23         FY-24
2           NaN           NaN           NaN           NaN           NaN
3           NaN           NaN           NaN           NaN           NaN
4  1,176,000.00  2,067,800.00  2,255,800.00  3,150,800.00          0.00
5  1,656,900.00  2,893,300.00  7,178,000.00  1,674,000.00          0.00
6  2,380,440.00  2,226,304.00  4,054,600.00  3,779,000.00          0.00
7  2,665,300.00  4,209,800.00  2,742,200.00  2,135,600.00          0.00
8    301,800.00    535,300.00    486,100.00    844,200.00          0.00
9    225,200.00    417,200.00    134,200.00    153,000.00          0.00

[10 rows x 1631 columns]

In [10]:
print(USA_data.head(10))

  Identifier                    Company Name     ISIN Code Ticker Symbol  \
0        NaN                             NaN           NaN           NaN
1        NaN                             NaN           NaN           NaN
2  537910017                             NaN           NaN           NaN
3    .ONEUSD                             NaN           NaN           NaN
4      AFL.N                       Aflac Inc  US0010551028           AFL
5      ABT.N             Abbott Laboratories  US0028241000           ABT
6    ADBE.OQ                       Adobe Inc  US00724F1012          ADBE
7     AMD.OQ      Advanced Micro Devices Inc  US0079031078           AMD
8      APD.N  Air Products and Chemicals Inc  US0091581068           APD
9      ALB.N                  Albemarle Corp  US0126531013           ALB

        Country of Exchange  \
0                       NaN
1                       NaN
2                       NaN
3                       NaN
4  United States of America
5  United States of America
6  United States of America
7  United States of America
8  United States of America
9  United States of America

                        NAICS National Industry Name  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4       Direct Health and Medical Insurance Carriers
5  Electromedical and Electrotherapeutic Apparatu...
6                                Software Publishers
7     Semiconductor and Related Device Manufacturing
8                       Industrial Gas Manufacturing
9       Other Basic Inorganic Chemical Manufacturing

  ESG Score\nIn the last 25 FY  Unnamed: 8  Unnamed: 9 Unnamed: 10  ...  \
0    (Date)\nIn the last 25 FY         NaN         NaN         NaN  ...
1                          FY0        FY-1        FY-2        FY-3  ...
2                          NaN         NaN         NaN         NaN  ...
3                          NaN         NaN         NaN         NaN  ...
4                   31/12/2023  31/12/2022  31/12/2021  31/12/2020  ...
5                   31/12/2023  31/12/2022  31/12/2021  31/12/2020  ...
6                   01/12/2023  02/12/2022  03/12/2021  27/11/2020  ...
7                   30/12/2023  31/12/2022  25/12/2021  26/12/2020  ...
8                   30/09/2023  30/09/2022  30/09/2021  30/09/2020  ...
9                   31/12/2023  31/12/2022  31/12/2021  31/12/2020  ...

  Unnamed: 1622 Unnamed: 1623 Unnamed: 1624 Unnamed: 1625 Unnamed: 1626  \
0           NaN           NaN           NaN           NaN           NaN
1         FY-15         FY-16         FY-17         FY-18         FY-19
2           NaN           NaN           NaN           NaN           NaN
3           NaN           NaN           NaN           NaN           NaN
4  1,211,600.00  2,132,000.00  1,436,000.00          0.00          0.00
5  1,408,500.00  1,644,600.00  2,511,500.00          0.00          0.00
6    885,600.00  1,916,445.00  1,829,932.00          0.00          0.00
7  1,390,100.00  2,939,100.00  5,420,900.00          0.00          0.00
8    184,900.00    709,600.00    628,800.00          0.00          0.00
9    153,100.00    417,900.00    265,300.00          0.00          0.00

  Unnamed: 1627 Unnamed: 1628 Unnamed: 1629 Unnamed: 1630 Unnamed: 1631
0           NaN           NaN           NaN           NaN           NaN
1         FY-20         FY-21         FY-22         FY-23         FY-24
2           NaN           NaN           NaN           NaN           NaN
3           NaN           NaN           NaN           NaN           NaN
4  1,176,000.00  2,067,800.00  2,255,800.00  3,150,800.00          0.00
5  1,656,900.00  2,893,300.00  7,178,000.00  1,674,000.00          0.00
6  2,380,440.00  2,226,304.00  4,054,600.00  3,779,000.00          0.00
7  2,665,300.00  4,209,800.00  2,742,200.00  2,135,600.00          0.00
8    301,800.00    535,300.00    486,100.00    844,200.00          0.00
9    225,200.00    417,200.00    134,200.00    153,000.00          0.00

[10 rows x 1631 columns]

In [7]:
# Remove the first 10 rows of the dataset, since these contains only NaN's
USA_data = USA_data.iloc[4:].reset_index(drop=True)
# Remove the 'Size' column from the dataset

# Check the result
print(USA_data.head(20))

   Identifier                      Company Name     ISIN Code Ticker Symbol  \
0       AFL.N                         Aflac Inc  US0010551028           AFL
1       ABT.N               Abbott Laboratories  US0028241000           ABT
2     ADBE.OQ                         Adobe Inc  US00724F1012          ADBE
3      AMD.OQ        Advanced Micro Devices Inc  US0079031078           AMD
4       APD.N    Air Products and Chemicals Inc  US0091581068           APD
5       ALB.N                    Albemarle Corp  US0126531013           ALB
6       ALL.N                     Allstate Corp  US0200021014           ALL
7       HES.N                         Hess Corp  US42809H1077           HES
8       AXP.N               American Express Co  US0258161092           AXP
9       AIG.N  American International Group Inc  US0268747849           AIG
10      COR.N                       Cencora Inc  US03073E1055           COR
11      AME.N                        AMETEK Inc  US0311001004           AME
12    AMGN.OQ                         Amgen Inc  US0311621009          AMGN
13      AON.N                           Aon PLC  IE00BLP1HW54           AON
14    AAPL.OQ                         Apple Inc  US0378331005          AAPL
15    AMAT.OQ             Applied Materials Inc  US0382221051          AMAT
16      ADM.N         Archer-Daniels-Midland Co  US0394831020           ADM
17    ADSK.OQ                      Autodesk Inc  US0527691069          ADSK
18     ADP.OQ     Automatic Data Processing Inc  US0530151036           ADP
19      AVB.N         AvalonBay Communities Inc  US0534841012           AVB

         Country of Exchange  \
0   United States of America
1   United States of America
2   United States of America
3   United States of America
4   United States of America
5   United States of America
6   United States of America
7   United States of America
8   United States of America
9   United States of America
10  United States of America
11  United States of America
12  United States of America
13  United States of America
14  United States of America
15  United States of America
16  United States of America
17  United States of America
18  United States of America
19  United States of America

                         NAICS National Industry Name  \
0        Direct Health and Medical Insurance Carriers
1   Electromedical and Electrotherapeutic Apparatu...
2                                 Software Publishers
3      Semiconductor and Related Device Manufacturing
4                        Industrial Gas Manufacturing
5        Other Basic Inorganic Chemical Manufacturing
6     Direct Property and Casualty Insurance Carriers
7                          Crude Petroleum Extraction
8                                 Credit Card Issuing
9     Direct Property and Casualty Insurance Carriers
10  Drugs and Druggists' Sundries Merchant Wholesa...
11  Instruments and Related Products Manufacturing...
12  Research and Development in Biotechnology (exc...
13                  Insurance Agencies and Brokerages
14  Radio and Television Broadcasting and Wireless...
15              Semiconductor Machinery Manufacturing
16         All Other Miscellaneous Food Manufacturing
17                                Software Publishers
18               Custom Computer Programming Services
19     Lessors of Residential Buildings and Dwellings

   ESG Score\nIn the last 25 FY  Unnamed: 8  Unnamed: 9 Unnamed: 10  ...  \
0                    31/12/2023  31/12/2022  31/12/2021  31/12/2020  ...
1                    31/12/2023  31/12/2022  31/12/2021  31/12/2020  ...
2                    01/12/2023  02/12/2022  03/12/2021  27/11/2020  ...
3                    30/12/2023  31/12/2022  25/12/2021  26/12/2020  ...
4                    30/09/2023  30/09/2022  30/09/2021  30/09/2020  ...
5                    31/12/2023  31/12/2022  31/12/2021  31/12/2020  ...
6                    31/12/2022  31/12/2021  31/12/2020  31/12/2019  ...
7                    31/12/2022  31/12/2021  31/12/2020  31/12/2019  ...
8                    31/12/2023  31/12/2022  31/12/2021  31/12/2020  ...
9                    31/12/2022  31/12/2021  31/12/2020  31/12/2019  ...
10                   30/09/2023  30/09/2022  30/09/2021  30/09/2020  ...
11                   31/12/2022  31/12/2021  31/12/2020  31/12/2019  ...
12                   31/12/2022  31/12/2021  31/12/2020  31/12/2019  ...
13                   31/12/2023  31/12/2022  31/12/2021  31/12/2020  ...
14                   30/09/2023  24/09/2022  25/09/2021  26/09/2020  ...
15                   29/10/2023  30/10/2022  31/10/2021  25/10/2020  ...
16                   31/12/2023  31/12/2022  31/12/2021  31/12/2020  ...
17                   31/01/2024  31/01/2023  31/01/2022  31/01/2021  ...
18                   30/06/2023  30/06/2022  30/06/2021  30/06/2020  ...
19                   31/12/2023  31/12/2022  31/12/2021  31/12/2020  ...

    Unnamed: 1622   Unnamed: 1623   Unnamed: 1624 Unnamed: 1625 Unnamed: 1626  \
0    1,211,600.00    2,132,000.00    1,436,000.00          0.00          0.00
1    1,408,500.00    1,644,600.00    2,511,500.00          0.00          0.00
2      885,600.00    1,916,445.00    1,829,932.00          0.00          0.00
3    1,390,100.00    2,939,100.00    5,420,900.00          0.00          0.00
4      184,900.00      709,600.00      628,800.00          0.00          0.00
5      153,100.00      417,900.00      265,300.00          0.00          0.00
6      804,100.00    1,183,500.00    1,307,400.00          0.00          0.00
7      506,900.00    1,269,900.00    1,241,600.00          0.00          0.00
8    1,350,300.00    3,404,500.00    3,755,000.00          0.00          0.00
9      543,200.00      355,010.00      258,665.00          0.00          0.00
10     663,300.00      928,400.00      746,600.00          0.00          0.00
11     251,999.00      630,224.00      660,824.00          0.00          0.00
12   1,688,991.00    2,459,584.00    3,515,843.00          0.00          0.00
13     409,400.00      847,200.00      803,100.00          0.00          0.00
14  97,567,217.00  223,636,139.00  231,454,783.00          0.00          0.00
15   3,191,578.00    3,700,500.00    3,442,777.00          0.00          0.00
16     865,100.00    1,168,000.00    2,602,400.00          0.00          0.00
17     625,045.00    1,081,644.00      722,266.00          0.00          0.00
18     706,972.00    1,514,359.00      618,200.00          0.00          0.00
19     359,900.00      711,400.00      389,000.00          0.00          0.00

     Unnamed: 1627  Unnamed: 1628   Unnamed: 1629   Unnamed: 1630  \
0     1,176,000.00   2,067,800.00    2,255,800.00    3,150,800.00
1     1,656,900.00   2,893,300.00    7,178,000.00    1,674,000.00
2     2,380,440.00   2,226,304.00    4,054,600.00    3,779,000.00
3     2,665,300.00   4,209,800.00    2,742,200.00    2,135,600.00
4       301,800.00     535,300.00      486,100.00      844,200.00
5       225,200.00     417,200.00      134,200.00      153,000.00
6       812,200.00   1,206,200.00    1,515,400.00    1,540,400.00
7       876,300.00   2,074,202.00    1,156,201.00    1,037,401.00
8     1,626,800.00   2,059,900.00    2,595,800.00    3,975,000.00
9       129,125.00     161,275.00      227,615.00      135,240.00
10    3,584,000.00  32,948,800.00    2,181,200.00    1,923,600.00
11      537,636.00     447,524.00    1,288,573.00      666,898.00
12    1,848,798.00   3,239,642.00   10,271,700.00   10,050,400.00
13      544,500.00     637,600.00      761,500.00    2,017,500.00
14  147,026,747.00  95,190,575.00  179,457,779.00  138,112,938.00
15    5,529,295.00  10,048,730.00   17,513,700.00   14,543,800.00
16      842,000.00   1,166,300.00    1,095,700.00    1,168,100.00
17      857,061.00   1,284,962.00    1,154,200.00    1,739,200.00
18      859,500.00   1,738,100.00    1,882,100.00    1,091,900.00
19      195,600.00     256,200.00      336,800.00       83,500.00

   Unnamed: 1631
0           0.00
1           0.00
2           0.00
3           0.00
4           0.00
5           0.00
6           0.00
7           0.00
8           0.00
9           0.00
10          0.00
11          0.00
12          0.00
13          0.00
14          0.00
15          0.00
16          0.00
17          0.00
18          0.00
19          0.00

[20 rows x 1631 columns]

In [38]:
USA_data.iloc[:, 6] #first column of dates for the ESG score, last is at 30
USA_data.iloc[:, 31] #first esg score, .last is at 55

0      42.65
1      84.15
2      68.41
3      70.30
4      78.06
       ...
310    63.78
311    67.95
312    65.62
313    70.23
314    81.24
Name: Unnamed: 32, Length: 315, dtype: object

In [40]:
# Convert all ESG date columns (6 to 31) to datetime and extract years as integers
for i in range(6, 32):
    USA_data[f'Year_{i}'] = pd.to_datetime(USA_data.iloc[:, i], format='%d/%m/%Y', errors='coerce').dt.year.astype('Int64')

# Select company-related columns
company_info_columns = ['Company Name', 'ISIN Code', 'Ticker Symbol', 'Country of Exchange', 'NAICS National Industry Name']
company_info = USA_data[company_info_columns]

# Create an empty DataFrame for ESG scores
esg_by_year = pd.DataFrame()

# Get all unique years from all date columns, ensuring they are integers
all_years = sorted(set(USA_data[[f'Year_{i}' for i in range(6, 32)]].stack().dropna().astype(int).unique()), reverse=True)

# Initialize an empty DataFrame to store ESG scores
esg_scores_per_year = pd.DataFrame(index=USA_data.index)

# Loop through each row to correctly place ESG scores in the right year columns
for index, row in USA_data.iterrows():
    for i in range(6, 32):  # Date columns
        year = row[f'Year_{i}']  # Extract the year
        
        if pd.notna(year):  # Ensure the year is valid
            year = int(year)  # Convert to integer
            esg_score_column = USA_data.columns[i + 25]  # ESG score column (offset by 25)
            esg_scores_per_year.at[index, f"ESG_score_{year}"] = row[esg_score_column]

# Sort columns from most recent year to oldest
esg_scores_per_year = esg_scores_per_year[sorted(esg_scores_per_year.columns, key=lambda x: int(x.split('_')[-1]), reverse=True)]

# Concatenate company info with sorted ESG scores
esg_by_year = pd.concat([company_info, esg_scores_per_year], axis=1)

# Display the resulting DataFrame
print(esg_by_year)

                       Company Name     ISIN Code Ticker Symbol  \
0                         Aflac Inc  US0010551028           AFL
1               Abbott Laboratories  US0028241000           ABT
2                         Adobe Inc  US00724F1012          ADBE
3        Advanced Micro Devices Inc  US0079031078           AMD
4    Air Products and Chemicals Inc  US0091581068           APD
..                              ...           ...           ...
310                     Corteva Inc  US22052L1044          CTVA
311                       Amcor PLC  JE00BJ1F3079          AMCR
312             Carrier Global Corp  US14448C1045          CARR
313             Otis Worldwide Corp  US68902V1070          OTIS
314            Smurfit WestRock PLC  IE00028FXN24            SW

          Country of Exchange  \
0    United States of America
1    United States of America
2    United States of America
3    United States of America
4    United States of America
..                        ...
310  United States of America
311  United States of America
312  United States of America
313  United States of America
314  United States of America

                          NAICS National Industry Name ESG_score_2024  \
0         Direct Health and Medical Insurance Carriers            NaN
1    Electromedical and Electrotherapeutic Apparatu...            NaN
2                                  Software Publishers            NaN
3       Semiconductor and Related Device Manufacturing            NaN
4                         Industrial Gas Manufacturing            NaN
..                                                 ...            ...
310                 Farm Supplies Merchant Wholesalers            NaN
311  Plastics Packaging Film and Sheet (including L...          67.95
312  Air-Conditioning and Warm Air Heating Equipmen...            NaN
313         Elevator and Moving Stairway Manufacturing            NaN
314                All Other Business Support Services            NaN

    ESG_score_2023 ESG_score_2022 ESG_score_2021 ESG_score_2020  ...  \
0            42.65          45.78          53.49          52.79  ...
1            84.15          83.23          80.63          80.55  ...
2            68.41          70.72          75.67          74.72  ...
3            70.30          67.79          71.20          65.80  ...
4            78.06          81.90          83.95          79.62  ...
..             ...            ...            ...            ...  ...
310          63.78          65.35          54.33          55.98  ...
311          69.88          68.66          71.53          71.28  ...
312            NaN          65.62          59.96          59.67  ...
313          70.23          63.33          66.43          60.97  ...
314            NaN          81.24          83.02          83.75  ...

    ESG_score_2005 ESG_score_2004 ESG_score_2003 ESG_score_2002  \
0            39.42          53.82          48.13          45.85
1            66.87          27.36          40.67          39.86
2            46.41          49.65          56.08          46.95
3            46.22          43.51          36.84          46.06
4            41.15            NaN            NaN            NaN
..             ...            ...            ...            ...
310            NaN            NaN            NaN            NaN
311          34.07          39.04            NaN            NaN
312            NaN            NaN            NaN            NaN
313            NaN            NaN            NaN            NaN
314            NaN            NaN            NaN            NaN

    ESG_score_2001 ESG_score_2000 ESG_score_1999 ESG_score_1998  \
0              NaN            NaN            NaN            NaN
1              NaN            NaN            NaN            NaN
2              NaN            NaN            NaN            NaN
3              NaN            NaN            NaN            NaN
4              NaN            NaN            NaN            NaN
..             ...            ...            ...            ...
310            NaN            NaN            NaN            NaN
311            NaN            NaN            NaN            NaN
312            NaN            NaN            NaN            NaN
313            NaN            NaN            NaN            NaN
314            NaN            NaN            NaN            NaN

    ESG_score_1997 ESG_score_1996
0              NaN            NaN
1              NaN            NaN
2              NaN            NaN
3              NaN            NaN
4              NaN            NaN
..             ...            ...
310            NaN            NaN
311            NaN            NaN
312            NaN            NaN
313            NaN            NaN
314            NaN            NaN

[315 rows x 34 columns]

In [56]:
USA_data.iloc[:, 56] #first column of dates for the environmental pillar score, last is at 80
USA_data.iloc[:, 81] #first environmental pillar score, .last is at 105

0      49.68
1      78.75
2      75.12
3      70.83
4      87.37
       ...
310    58.74
311    63.06
312    50.65
313    46.51
314    77.37
Name: Unnamed: 82, Length: 315, dtype: object

In [58]:
# Convert all ESG date columns (6 to 31) to datetime and extract years
for i in range(6, 32):
    USA_data[f'Year_{i}'] = pd.to_datetime(USA_data.iloc[:, i], format='%d/%m/%Y', errors='coerce').dt.year

# Select company-related columns
company_info_columns = ['Company Name', 'ISIN Code', 'Ticker Symbol', 'Country of Exchange', 'NAICS National Industry Name']
company_info = USA_data[company_info_columns]

# Initialize empty DataFrames to store ESG scores and environmental pillar scores
esg_scores_per_year = pd.DataFrame(index=USA_data.index)
env_pillar_scores_per_year = pd.DataFrame(index=USA_data.index)

# Process ESG scores
for index, row in USA_data.iterrows():
    for i in range(6, 32):  # ESG date columns
        year = row[f'Year_{i}']
        esg_score_column = USA_data.columns[i + 25]  # Corresponding ESG score column
        
        if pd.notna(year):
            esg_scores_per_year.at[index, f"ESG_score_{int(year)}"] = row[esg_score_column]

# Process Environmental Pillar Scores
for index, row in USA_data.iterrows():
    for i in range(56, 81):  # Environmental pillar score date columns
        year = row[f'Year_{i - 50}']  # Match with the ESG years
        env_score_column = USA_data.columns[i + 25]  # Corresponding environmental pillar score column
        
        if pd.notna(year):
            env_pillar_scores_per_year.at[index, f"Env_score_{int(year)}"] = row[env_score_column]

# Sort columns from most recent year to oldest
esg_scores_per_year = esg_scores_per_year[sorted(esg_scores_per_year.columns, key=lambda x: int(x.split('_')[-1]), reverse=True)]
env_pillar_scores_per_year = env_pillar_scores_per_year[sorted(env_pillar_scores_per_year.columns, key=lambda x: int(x.split('_')[-1]), reverse=True)]

# Combine everything into a single DataFrame
esg_by_year = pd.concat([company_info, esg_scores_per_year, env_pillar_scores_per_year], axis=1)

# Display the resulting DataFrame
print(esg_by_year)

                       Company Name     ISIN Code Ticker Symbol  \
0                         Aflac Inc  US0010551028           AFL
1               Abbott Laboratories  US0028241000           ABT
2                         Adobe Inc  US00724F1012          ADBE
3        Advanced Micro Devices Inc  US0079031078           AMD
4    Air Products and Chemicals Inc  US0091581068           APD
..                              ...           ...           ...
310                     Corteva Inc  US22052L1044          CTVA
311                       Amcor PLC  JE00BJ1F3079          AMCR
312             Carrier Global Corp  US14448C1045          CARR
313             Otis Worldwide Corp  US68902V1070          OTIS
314            Smurfit WestRock PLC  IE00028FXN24            SW

          Country of Exchange  \
0    United States of America
1    United States of America
2    United States of America
3    United States of America
4    United States of America
..                        ...
310  United States of America
311  United States of America
312  United States of America
313  United States of America
314  United States of America

                          NAICS National Industry Name ESG_score_2024  \
0         Direct Health and Medical Insurance Carriers            NaN
1    Electromedical and Electrotherapeutic Apparatu...            NaN
2                                  Software Publishers            NaN
3       Semiconductor and Related Device Manufacturing            NaN
4                         Industrial Gas Manufacturing            NaN
..                                                 ...            ...
310                 Farm Supplies Merchant Wholesalers            NaN
311  Plastics Packaging Film and Sheet (including L...          67.95
312  Air-Conditioning and Warm Air Heating Equipmen...            NaN
313         Elevator and Moving Stairway Manufacturing            NaN
314                All Other Business Support Services            NaN

    ESG_score_2023 ESG_score_2022 ESG_score_2021 ESG_score_2020  ...  \
0            42.65          45.78          53.49          52.79  ...
1            84.15          83.23          80.63          80.55  ...
2            68.41          70.72          75.67          74.72  ...
3            70.30          67.79          71.20          65.80  ...
4            78.06          81.90          83.95          79.62  ...
..             ...            ...            ...            ...  ...
310          63.78          65.35          54.33          55.98  ...
311          69.88          68.66          71.53          71.28  ...
312            NaN          65.62          59.96          59.67  ...
313          70.23          63.33          66.43          60.97  ...
314            NaN          81.24          83.02          83.75  ...

    Env_score_2005 Env_score_2004 Env_score_2003 Env_score_2002  \
0            27.21          28.33          28.42          28.38
1            35.63          44.94          26.95          31.20
2            15.79           7.07           0.00           0.00
3            37.83          35.39          19.58          33.06
4            48.24            NaN            NaN            NaN
..             ...            ...            ...            ...
310            NaN            NaN            NaN            NaN
311          37.19          27.48            NaN            NaN
312            NaN            NaN            NaN            NaN
313            NaN            NaN            NaN            NaN
314            NaN            NaN            NaN            NaN

    Env_score_2001 Env_score_2000 Env_score_1999 Env_score_1998  \
0              NaN            NaN            NaN            NaN
1              NaN            NaN            NaN            NaN
2              NaN            NaN            NaN            NaN
3              NaN            NaN            NaN            NaN
4              NaN            NaN            NaN            NaN
..             ...            ...            ...            ...
310            NaN            NaN            NaN            NaN
311            NaN            NaN            NaN            NaN
312            NaN            NaN            NaN            NaN
313            NaN            NaN            NaN            NaN
314            NaN            NaN            NaN            NaN

    Env_score_1997 Env_score_1996
0              NaN            NaN
1              NaN            NaN
2              NaN            NaN
3              NaN            NaN
4              NaN            NaN
..             ...            ...
310            NaN            NaN
311            NaN            NaN
312            NaN            NaN
313            NaN            NaN
314            NaN            NaN

[315 rows x 63 columns]

In [72]:
USA_data.iloc[:, 106] #first column of dates for the social pillar score, last is at 130
USA_data.iloc[:, 131] #first social pillar score, .last is at 155

0      46.01
1      86.30
2      76.97
3      69.52
4      75.90
       ...
310    59.36
311    62.65
312    79.52
313    74.45
314    84.02
Name: Unnamed: 132, Length: 315, dtype: object

In [74]:
# Convert all ESG date columns (6 to 31) to datetime and extract years
for i in range(6, 32):
    USA_data[f'Year_{i}'] = pd.to_datetime(USA_data.iloc[:, i], format='%d/%m/%Y', errors='coerce').dt.year

# Select company-related columns
company_info_columns = ['Company Name', 'ISIN Code', 'Ticker Symbol', 'Country of Exchange', 'NAICS National Industry Name']
company_info = USA_data[company_info_columns]

# Initialize empty DataFrames to store ESG scores, environmental pillar scores, and social pillar scores
esg_scores_per_year = pd.DataFrame(index=USA_data.index)
env_pillar_scores_per_year = pd.DataFrame(index=USA_data.index)
social_pillar_scores_per_year = pd.DataFrame(index=USA_data.index)

# Process ESG scores
for index, row in USA_data.iterrows():
    for i in range(6, 32):  # ESG date columns
        year = row[f'Year_{i}']
        esg_score_column = USA_data.columns[i + 25]  # Corresponding ESG score column
        
        if pd.notna(year):
            esg_scores_per_year.at[index, f"ESG_score_{int(year)}"] = row[esg_score_column]

# Process Environmental Pillar Scores
for index, row in USA_data.iterrows():
    for i in range(56, 81):  # Environmental pillar score date columns
        year = row[f'Year_{i - 50}']  # Match with the ESG years
        env_score_column = USA_data.columns[i + 25]  # Corresponding environmental pillar score column
        
        if pd.notna(year):
            env_pillar_scores_per_year.at[index, f"Env_score_{int(year)}"] = row[env_score_column]

# Process Social Pillar Scores
for index, row in USA_data.iterrows():
    for i in range(106, 131):  # Social pillar score date columns
        year = row[f'Year_{i - 100}']  # Match with the ESG years
        social_score_column = USA_data.columns[i + 25]  # Corresponding social pillar score column
        
        if pd.notna(year):
            social_pillar_scores_per_year.at[index, f"Social_score_{int(year)}"] = row[social_score_column]

# Sort columns from most recent year to oldest
esg_scores_per_year = esg_scores_per_year[sorted(esg_scores_per_year.columns, key=lambda x: int(x.split('_')[-1]), reverse=True)]
env_pillar_scores_per_year = env_pillar_scores_per_year[sorted(env_pillar_scores_per_year.columns, key=lambda x: int(x.split('_')[-1]), reverse=True)]
social_pillar_scores_per_year = social_pillar_scores_per_year[sorted(social_pillar_scores_per_year.columns, key=lambda x: int(x.split('_')[-1]), reverse=True)]

# Combine everything into a single DataFrame
esg_by_year = pd.concat([company_info, esg_scores_per_year, env_pillar_scores_per_year, social_pillar_scores_per_year], axis=1)

# Display the resulting DataFrame
print(esg_by_year)

                       Company Name     ISIN Code Ticker Symbol  \
0                         Aflac Inc  US0010551028           AFL
1               Abbott Laboratories  US0028241000           ABT
2                         Adobe Inc  US00724F1012          ADBE
3        Advanced Micro Devices Inc  US0079031078           AMD
4    Air Products and Chemicals Inc  US0091581068           APD
..                              ...           ...           ...
310                     Corteva Inc  US22052L1044          CTVA
311                       Amcor PLC  JE00BJ1F3079          AMCR
312             Carrier Global Corp  US14448C1045          CARR
313             Otis Worldwide Corp  US68902V1070          OTIS
314            Smurfit WestRock PLC  IE00028FXN24            SW

          Country of Exchange  \
0    United States of America
1    United States of America
2    United States of America
3    United States of America
4    United States of America
..                        ...
310  United States of America
311  United States of America
312  United States of America
313  United States of America
314  United States of America

                          NAICS National Industry Name ESG_score_2024  \
0         Direct Health and Medical Insurance Carriers            NaN
1    Electromedical and Electrotherapeutic Apparatu...            NaN
2                                  Software Publishers            NaN
3       Semiconductor and Related Device Manufacturing            NaN
4                         Industrial Gas Manufacturing            NaN
..                                                 ...            ...
310                 Farm Supplies Merchant Wholesalers            NaN
311  Plastics Packaging Film and Sheet (including L...          67.95
312  Air-Conditioning and Warm Air Heating Equipmen...            NaN
313         Elevator and Moving Stairway Manufacturing            NaN
314                All Other Business Support Services            NaN

    ESG_score_2023 ESG_score_2022 ESG_score_2021 ESG_score_2020  ...  \
0            42.65          45.78          53.49          52.79  ...
1            84.15          83.23          80.63          80.55  ...
2            68.41          70.72          75.67          74.72  ...
3            70.30          67.79          71.20          65.80  ...
4            78.06          81.90          83.95          79.62  ...
..             ...            ...            ...            ...  ...
310          63.78          65.35          54.33          55.98  ...
311          69.88          68.66          71.53          71.28  ...
312            NaN          65.62          59.96          59.67  ...
313          70.23          63.33          66.43          60.97  ...
314            NaN          81.24          83.02          83.75  ...

    Social_score_2005 Social_score_2004 Social_score_2003 Social_score_2002  \
0               29.90             59.92             66.06             47.68
1               64.64             24.93             30.66             42.23
2               70.94             71.55             69.41             68.40
3               43.83             29.51             32.71             33.36
4               30.73               NaN               NaN               NaN
..                ...               ...               ...               ...
310               NaN               NaN               NaN               NaN
311             23.73             23.94               NaN               NaN
312               NaN               NaN               NaN               NaN
313               NaN               NaN               NaN               NaN
314               NaN               NaN               NaN               NaN

    Social_score_2001 Social_score_2000 Social_score_1999 Social_score_1998  \
0                 NaN               NaN               NaN               NaN
1                 NaN               NaN               NaN               NaN
2                 NaN               NaN               NaN               NaN
3                 NaN               NaN               NaN               NaN
4                 NaN               NaN               NaN               NaN
..                ...               ...               ...               ...
310               NaN               NaN               NaN               NaN
311               NaN               NaN               NaN               NaN
312               NaN               NaN               NaN               NaN
313               NaN               NaN               NaN               NaN
314               NaN               NaN               NaN               NaN

    Social_score_1997 Social_score_1996
0                 NaN               NaN
1                 NaN               NaN
2                 NaN               NaN
3                 NaN               NaN
4                 NaN               NaN
..                ...               ...
310               NaN               NaN
311               NaN               NaN
312               NaN               NaN
313               NaN               NaN
314               NaN               NaN

[315 rows x 92 columns]

In [86]:
USA_data.iloc[:, 156] #first column of dates for the governance pillar score, last is at 180
USA_data.iloc[:, 181] #first governance pillar score, .last is at 205

0      41.14
1      83.84
2      59.04
3      70.98
4      65.26
       ...
310    80.16
311    84.44
312    65.37
313    92.98
314    82.48
Name: Unnamed: 182, Length: 315, dtype: object

In [88]:
# Convert all ESG date columns (6 to 31) to datetime and extract years
for i in range(6, 32):
    USA_data[f'Year_{i}'] = pd.to_datetime(USA_data.iloc[:, i], format='%d/%m/%Y', errors='coerce').dt.year

# Select company-related columns
company_info_columns = ['Company Name', 'ISIN Code', 'Ticker Symbol', 'Country of Exchange', 'NAICS National Industry Name']
company_info = USA_data[company_info_columns]

# Initialize empty DataFrames to store ESG and pillar scores
esg_scores_per_year = pd.DataFrame(index=USA_data.index)
env_pillar_scores_per_year = pd.DataFrame(index=USA_data.index)
social_pillar_scores_per_year = pd.DataFrame(index=USA_data.index)
gov_pillar_scores_per_year = pd.DataFrame(index=USA_data.index)

# Process ESG scores
for index, row in USA_data.iterrows():
    for i in range(6, 32):  # ESG date columns
        year = row[f'Year_{i}']
        esg_score_column = USA_data.columns[i + 25]  # Corresponding ESG score column
        
        if pd.notna(year):
            esg_scores_per_year.at[index, f"ESG_score_{int(year)}"] = row[esg_score_column]

# Process Environmental Pillar Scores
for index, row in USA_data.iterrows():
    for i in range(56, 81):  # Environmental pillar score date columns
        year = row[f'Year_{i - 50}']  # Match with the ESG years
        env_score_column = USA_data.columns[i + 25]  # Corresponding environmental pillar score column
        
        if pd.notna(year):
            env_pillar_scores_per_year.at[index, f"Env_score_{int(year)}"] = row[env_score_column]

# Process Social Pillar Scores
for index, row in USA_data.iterrows():
    for i in range(106, 131):  # Social pillar score date columns
        year = row[f'Year_{i - 100}']  # Match with the ESG years
        social_score_column = USA_data.columns[i + 25]  # Corresponding social pillar score column
        
        if pd.notna(year):
            social_pillar_scores_per_year.at[index, f"Social_score_{int(year)}"] = row[social_score_column]

# Process Governance Pillar Scores
for index, row in USA_data.iterrows():
    for i in range(156, 181):  # Governance pillar score date columns
        year = row[f'Year_{i - 150}']  # Match with the ESG years
        gov_score_column = USA_data.columns[i + 25]  # Corresponding governance pillar score column
        
        if pd.notna(year):
            gov_pillar_scores_per_year.at[index, f"Gov_score_{int(year)}"] = row[gov_score_column]

# Sort all score columns from most recent year to oldest
esg_scores_per_year = esg_scores_per_year[sorted(esg_scores_per_year.columns, key=lambda x: int(x.split('_')[-1]), reverse=True)]
env_pillar_scores_per_year = env_pillar_scores_per_year[sorted(env_pillar_scores_per_year.columns, key=lambda x: int(x.split('_')[-1]), reverse=True)]
social_pillar_scores_per_year = social_pillar_scores_per_year[sorted(social_pillar_scores_per_year.columns, key=lambda x: int(x.split('_')[-1]), reverse=True)]
gov_pillar_scores_per_year = gov_pillar_scores_per_year[sorted(gov_pillar_scores_per_year.columns, key=lambda x: int(x.split('_')[-1]), reverse=True)]

# Combine everything into a single DataFrame
esg_by_year = pd.concat([company_info, esg_scores_per_year, env_pillar_scores_per_year, social_pillar_scores_per_year, gov_pillar_scores_per_year], axis=1)

# Display the resulting DataFrame
print(esg_by_year)

                       Company Name     ISIN Code Ticker Symbol  \
0                         Aflac Inc  US0010551028           AFL
1               Abbott Laboratories  US0028241000           ABT
2                         Adobe Inc  US00724F1012          ADBE
3        Advanced Micro Devices Inc  US0079031078           AMD
4    Air Products and Chemicals Inc  US0091581068           APD
..                              ...           ...           ...
310                     Corteva Inc  US22052L1044          CTVA
311                       Amcor PLC  JE00BJ1F3079          AMCR
312             Carrier Global Corp  US14448C1045          CARR
313             Otis Worldwide Corp  US68902V1070          OTIS
314            Smurfit WestRock PLC  IE00028FXN24            SW

          Country of Exchange  \
0    United States of America
1    United States of America
2    United States of America
3    United States of America
4    United States of America
..                        ...
310  United States of America
311  United States of America
312  United States of America
313  United States of America
314  United States of America

                          NAICS National Industry Name ESG_score_2024  \
0         Direct Health and Medical Insurance Carriers            NaN
1    Electromedical and Electrotherapeutic Apparatu...            NaN
2                                  Software Publishers            NaN
3       Semiconductor and Related Device Manufacturing            NaN
4                         Industrial Gas Manufacturing            NaN
..                                                 ...            ...
310                 Farm Supplies Merchant Wholesalers            NaN
311  Plastics Packaging Film and Sheet (including L...          67.95
312  Air-Conditioning and Warm Air Heating Equipmen...            NaN
313         Elevator and Moving Stairway Manufacturing            NaN
314                All Other Business Support Services            NaN

    ESG_score_2023 ESG_score_2022 ESG_score_2021 ESG_score_2020  ...  \
0            42.65          45.78          53.49          52.79  ...
1            84.15          83.23          80.63          80.55  ...
2            68.41          70.72          75.67          74.72  ...
3            70.30          67.79          71.20          65.80  ...
4            78.06          81.90          83.95          79.62  ...
..             ...            ...            ...            ...  ...
310          63.78          65.35          54.33          55.98  ...
311          69.88          68.66          71.53          71.28  ...
312            NaN          65.62          59.96          59.67  ...
313          70.23          63.33          66.43          60.97  ...
314            NaN          81.24          83.02          83.75  ...

    Gov_score_2005 Gov_score_2004 Gov_score_2003 Gov_score_2002  \
0            63.66          64.64          43.26          58.99
1            84.40          22.35          60.25          40.77
2            34.47          43.57          61.42          42.56
3            60.23          76.37          64.36          82.62
4            46.27            NaN            NaN            NaN
..             ...            ...            ...            ...
310            NaN            NaN            NaN            NaN
311          46.79          82.33            NaN            NaN
312            NaN            NaN            NaN            NaN
313            NaN            NaN            NaN            NaN
314            NaN            NaN            NaN            NaN

    Gov_score_2001 Gov_score_2000 Gov_score_1999 Gov_score_1998  \
0              NaN            NaN            NaN            NaN
1              NaN            NaN            NaN            NaN
2              NaN            NaN            NaN            NaN
3              NaN            NaN            NaN            NaN
4              NaN            NaN            NaN            NaN
..             ...            ...            ...            ...
310            NaN            NaN            NaN            NaN
311            NaN            NaN            NaN            NaN
312            NaN            NaN            NaN            NaN
313            NaN            NaN            NaN            NaN
314            NaN            NaN            NaN            NaN

    Gov_score_1997 Gov_score_1996
0              NaN            NaN
1              NaN            NaN
2              NaN            NaN
3              NaN            NaN
4              NaN            NaN
..             ...            ...
310            NaN            NaN
311            NaN            NaN
312            NaN            NaN
313            NaN            NaN
314            NaN            NaN

[315 rows x 121 columns]

In [102]:
USA_data.iloc[:, 206] #first column of dates for the ESG combined score, last is at 230
USA_data.iloc[:, 231] #first ESG combined score, .last is at 255

0      42.65
1      45.50
2      47.44
3      70.30
4      74.81
       ...
310    39.24
311    42.31
312    65.62
313    70.23
314    73.95
Name: Unnamed: 232, Length: 315, dtype: object

In [104]:
# Convert all ESG date columns (6 to 31) to datetime and extract years
for i in range(6, 32):
    USA_data[f'Year_{i}'] = pd.to_datetime(USA_data.iloc[:, i], format='%d/%m/%Y', errors='coerce').dt.year

# Select company-related columns
company_info_columns = ['Company Name', 'ISIN Code', 'Ticker Symbol', 'Country of Exchange', 'NAICS National Industry Name']
company_info = USA_data[company_info_columns]

# Initialize empty DataFrames to store ESG and pillar scores
esg_scores_per_year = pd.DataFrame(index=USA_data.index)
env_pillar_scores_per_year = pd.DataFrame(index=USA_data.index)
social_pillar_scores_per_year = pd.DataFrame(index=USA_data.index)
gov_pillar_scores_per_year = pd.DataFrame(index=USA_data.index)
esg_combined_scores_per_year = pd.DataFrame(index=USA_data.index)

# Process ESG scores
for index, row in USA_data.iterrows():
    for i in range(6, 32):  # ESG date columns
        year = row[f'Year_{i}']
        esg_score_column = USA_data.columns[i + 25]  # Corresponding ESG score column
        
        if pd.notna(year):
            esg_scores_per_year.at[index, f"ESG_score_{int(year)}"] = row[esg_score_column]

# Process Environmental Pillar Scores
for index, row in USA_data.iterrows():
    for i in range(56, 81):  # Environmental pillar score date columns
        year = row[f'Year_{i - 50}']  # Match with the ESG years
        env_score_column = USA_data.columns[i + 25]  # Corresponding environmental pillar score column
        
        if pd.notna(year):
            env_pillar_scores_per_year.at[index, f"Env_score_{int(year)}"] = row[env_score_column]

# Process Social Pillar Scores
for index, row in USA_data.iterrows():
    for i in range(106, 131):  # Social pillar score date columns
        year = row[f'Year_{i - 100}']  # Match with the ESG years
        social_score_column = USA_data.columns[i + 25]  # Corresponding social pillar score column
        
        if pd.notna(year):
            social_pillar_scores_per_year.at[index, f"Social_score_{int(year)}"] = row[social_score_column]

# Process Governance Pillar Scores
for index, row in USA_data.iterrows():
    for i in range(156, 181):  # Governance pillar score date columns
        year = row[f'Year_{i - 150}']  # Match with the ESG years
        gov_score_column = USA_data.columns[i + 25]  # Corresponding governance pillar score column
        
        if pd.notna(year):
            gov_pillar_scores_per_year.at[index, f"Gov_score_{int(year)}"] = row[gov_score_column]

# Process ESG Combined Scores
for index, row in USA_data.iterrows():
    for i in range(206, 231):  # ESG combined score date columns
        year = row[f'Year_{i - 200}']  # Match with the ESG years
        esg_combined_score_column = USA_data.columns[i + 25]  # Corresponding ESG combined score column
        
        if pd.notna(year):
            esg_combined_scores_per_year.at[index, f"ESG_combined_score_{int(year)}"] = row[esg_combined_score_column]

# Sort all score columns from most recent year to oldest
esg_scores_per_year = esg_scores_per_year[sorted(esg_scores_per_year.columns, key=lambda x: int(x.split('_')[-1]), reverse=True)]
env_pillar_scores_per_year = env_pillar_scores_per_year[sorted(env_pillar_scores_per_year.columns, key=lambda x: int(x.split('_')[-1]), reverse=True)]
social_pillar_scores_per_year = social_pillar_scores_per_year[sorted(social_pillar_scores_per_year.columns, key=lambda x: int(x.split('_')[-1]), reverse=True)]
gov_pillar_scores_per_year = gov_pillar_scores_per_year[sorted(gov_pillar_scores_per_year.columns, key=lambda x: int(x.split('_')[-1]), reverse=True)]
esg_combined_scores_per_year = esg_combined_scores_per_year[sorted(esg_combined_scores_per_year.columns, key=lambda x: int(x.split('_')[-1]), reverse=True)]

# Combine everything into a single DataFrame
esg_by_year = pd.concat([company_info, esg_scores_per_year, env_pillar_scores_per_year, social_pillar_scores_per_year, gov_pillar_scores_per_year, esg_combined_scores_per_year], axis=1)

# Display the resulting DataFrame
print(esg_by_year)

                       Company Name     ISIN Code Ticker Symbol  \
0                         Aflac Inc  US0010551028           AFL
1               Abbott Laboratories  US0028241000           ABT
2                         Adobe Inc  US00724F1012          ADBE
3        Advanced Micro Devices Inc  US0079031078           AMD
4    Air Products and Chemicals Inc  US0091581068           APD
..                              ...           ...           ...
310                     Corteva Inc  US22052L1044          CTVA
311                       Amcor PLC  JE00BJ1F3079          AMCR
312             Carrier Global Corp  US14448C1045          CARR
313             Otis Worldwide Corp  US68902V1070          OTIS
314            Smurfit WestRock PLC  IE00028FXN24            SW

          Country of Exchange  \
0    United States of America
1    United States of America
2    United States of America
3    United States of America
4    United States of America
..                        ...
310  United States of America
311  United States of America
312  United States of America
313  United States of America
314  United States of America

                          NAICS National Industry Name ESG_score_2024  \
0         Direct Health and Medical Insurance Carriers            NaN
1    Electromedical and Electrotherapeutic Apparatu...            NaN
2                                  Software Publishers            NaN
3       Semiconductor and Related Device Manufacturing            NaN
4                         Industrial Gas Manufacturing            NaN
..                                                 ...            ...
310                 Farm Supplies Merchant Wholesalers            NaN
311  Plastics Packaging Film and Sheet (including L...          67.95
312  Air-Conditioning and Warm Air Heating Equipmen...            NaN
313         Elevator and Moving Stairway Manufacturing            NaN
314                All Other Business Support Services            NaN

    ESG_score_2023 ESG_score_2022 ESG_score_2021 ESG_score_2020  ...  \
0            42.65          45.78          53.49          52.79  ...
1            84.15          83.23          80.63          80.55  ...
2            68.41          70.72          75.67          74.72  ...
3            70.30          67.79          71.20          65.80  ...
4            78.06          81.90          83.95          79.62  ...
..             ...            ...            ...            ...  ...
310          63.78          65.35          54.33          55.98  ...
311          69.88          68.66          71.53          71.28  ...
312            NaN          65.62          59.96          59.67  ...
313          70.23          63.33          66.43          60.97  ...
314            NaN          81.24          83.02          83.75  ...

    ESG_combined_score_2005 ESG_combined_score_2004 ESG_combined_score_2003  \
0                     39.42                   53.82                   48.13
1                     65.58                   27.36                   40.67
2                     46.41                   49.65                   56.08
3                     46.22                   43.51                   36.84
4                     41.15                     NaN                     NaN
..                      ...                     ...                     ...
310                     NaN                     NaN                     NaN
311                   34.07                   39.04                     NaN
312                     NaN                     NaN                     NaN
313                     NaN                     NaN                     NaN
314                     NaN                     NaN                     NaN

    ESG_combined_score_2002 ESG_combined_score_2001 ESG_combined_score_2000  \
0                     45.85                     NaN                     NaN
1                     39.86                     NaN                     NaN
2                     46.95                     NaN                     NaN
3                     46.06                     NaN                     NaN
4                       NaN                     NaN                     NaN
..                      ...                     ...                     ...
310                     NaN                     NaN                     NaN
311                     NaN                     NaN                     NaN
312                     NaN                     NaN                     NaN
313                     NaN                     NaN                     NaN
314                     NaN                     NaN                     NaN

    ESG_combined_score_1999 ESG_combined_score_1998 ESG_combined_score_1997  \
0                       NaN                     NaN                     NaN
1                       NaN                     NaN                     NaN
2                       NaN                     NaN                     NaN
3                       NaN                     NaN                     NaN
4                       NaN                     NaN                     NaN
..                      ...                     ...                     ...
310                     NaN                     NaN                     NaN
311                     NaN                     NaN                     NaN
312                     NaN                     NaN                     NaN
313                     NaN                     NaN                     NaN
314                     NaN                     NaN                     NaN

    ESG_combined_score_1996
0                       NaN
1                       NaN
2                       NaN
3                       NaN
4                       NaN
..                      ...
310                     NaN
311                     NaN
312                     NaN
313                     NaN
314                     NaN

[315 rows x 150 columns]

In [108]:
# Export to Excel
esg_by_year.to_excel('USA_ESG.xlsx', index=False, engine='openpyxl')

# Finance data USA

In [1]:
data = pd.read_csv(r"file")
print(data.head())

NameError: name 'pd' is not defined

In [119]:
# Remove the first 10 rows of the dataset, since these contains only NaN's
data = data.iloc[4:].reset_index(drop=True)
# Remove the 'Size' column from the dataset

# Check the result
print(data.head(20))

   Identifier                      Company Name     ISIN Code  \
0       AFL.N                         Aflac Inc  US0010551028
1       ABT.N               Abbott Laboratories  US0028241000
2     ADBE.OQ                         Adobe Inc  US00724F1012
3      AMD.OQ        Advanced Micro Devices Inc  US0079031078
4       APD.N    Air Products and Chemicals Inc  US0091581068
5       ALB.N                    Albemarle Corp  US0126531013
6       ALL.N                     Allstate Corp  US0200021014
7       HES.N                         Hess Corp  US42809H1077
8       AXP.N               American Express Co  US0258161092
9       AIG.N  American International Group Inc  US0268747849
10      COR.N                       Cencora Inc  US03073E1055
11      AME.N                        AMETEK Inc  US0311001004
12    AMGN.OQ                         Amgen Inc  US0311621009
13      AON.N                           Aon PLC  IE00BLP1HW54
14    AAPL.OQ                         Apple Inc  US0378331005
15    AMAT.OQ             Applied Materials Inc  US0382221051
16      ADM.N         Archer-Daniels-Midland Co  US0394831020
17    ADSK.OQ                      Autodesk Inc  US0527691069
18     ADP.OQ     Automatic Data Processing Inc  US0530151036
19      AVB.N         AvalonBay Communities Inc  US0534841012

   Return On Equity - Actual\nIn the last 25 FY  Unnamed: 4  Unnamed: 5  \
0                                    05/02/2025  31/01/2024  01/02/2023
1                                    22/01/2025  24/01/2024  25/01/2023
2                                    11/12/2024  13/12/2023  15/12/2022
3                                    04/02/2025  30/01/2024  31/01/2023
4                                    07/11/2024  07/11/2023  03/11/2022
5                                    12/02/2025  14/02/2024  15/02/2023
6                                    05/02/2025  07/02/2024  01/02/2023
7                                    29/01/2025  31/01/2024  25/01/2023
8                                    24/01/2025  26/01/2024  27/01/2023
9                                    11/02/2025  13/02/2024  15/02/2023
10                                   06/11/2024  02/11/2023  30/11/2022
11                                   04/02/2025  06/02/2024  02/02/2023
12                                   04/02/2025  06/02/2024  31/01/2023
13                                   31/01/2025  29/02/2024  03/02/2023
14                                   31/10/2024  02/11/2023  27/10/2022
15                                   14/11/2024  16/11/2023  17/11/2022
16                                   04/02/2025  12/03/2024  26/01/2023
17                                   27/02/2025  29/02/2024  23/02/2023
18                                   31/07/2024  26/07/2023  27/07/2022
19                                   05/02/2025  31/01/2024  08/02/2023

    Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  ... Unnamed: 294  \
0   02/02/2022  03/02/2021  04/02/2020  31/01/2019  ...         0.56
1   26/01/2022  27/01/2021  22/01/2020  23/01/2019  ...         1.56
2   16/12/2021  10/12/2020  12/12/2019  13/12/2018  ...         0.00
3   01/02/2022  26/01/2021  28/01/2020  29/01/2019  ...         0.00
4   04/11/2021  11/11/2020  07/11/2019  06/11/2018  ...         1.79
5   16/02/2022  17/02/2021  19/02/2020  20/02/2019  ...         0.50
6   02/02/2022  03/02/2021  04/02/2020  05/02/2019  ...         0.80
7   26/01/2022  27/01/2021  29/01/2020  30/01/2019  ...         0.40
8   25/01/2022  26/01/2021  24/01/2020  17/01/2019  ...         0.72
9   16/02/2022  16/02/2021  13/02/2020  13/02/2019  ...         0.00
10  04/11/2021  30/11/2020  07/11/2019  06/11/2018  ...         0.21
11  03/02/2022  04/02/2021  05/02/2020  05/02/2019  ...         0.11
12  07/02/2022  02/02/2021  30/01/2020  29/01/2019  ...         0.00
13  04/02/2022  05/02/2021  31/01/2020  01/02/2019  ...         0.60
14  28/10/2021  29/10/2020  30/10/2019  01/11/2018  ...         0.00
15  18/11/2021  12/11/2020  14/11/2019  15/11/2018  ...         0.24
16  25/01/2022  26/01/2021  29/01/2020  05/02/2019  ...          NaN
17  24/02/2022  25/02/2021  29/02/2020  28/02/2019  ...         0.00
18  28/07/2021  29/07/2020  31/07/2019  01/08/2018  ...         1.28
19  02/02/2022  04/02/2021  05/02/2020  04/02/2019  ...         3.57

   Unnamed: 295 Unnamed: 296 Unnamed: 297 Unnamed: 298 Unnamed: 299  \
0          0.48         0.40         0.28         0.22         0.19
1          1.41         1.27         1.18         1.10         1.04
2          0.00         0.00         0.00         0.01         0.03
3          0.00         0.00         0.00         0.00         0.00
4          1.70         1.48         1.25         1.25         1.04
5          0.48         0.42         0.35         0.31         0.29
6          1.64         1.52         1.40         1.28         1.12
7          0.40         0.40         0.40         1.20         0.40
8          0.72         0.63         0.57         0.48         0.44
9           NaN        14.60        13.20        11.00         5.60
10         0.15         0.10         0.05         0.03         0.03
11         0.11         0.11         0.08         0.07         0.01
12         0.00         0.00         0.00         0.00         0.00
13         0.60         0.60         0.60         0.60         0.60
14         0.00         0.00         0.00         0.00         0.00
15         0.24         0.23         0.16         0.09         0.00
16          NaN          NaN          NaN          NaN          NaN
17         0.00         0.00          NaN          NaN          NaN
18         1.10         0.88         0.71         0.61         0.54
19         5.38         3.40         3.12          NaN         2.80

   Unnamed: 300 Unnamed: 301 Unnamed: 302 Unnamed: 303
0          0.15         0.18         0.10         5.48
1          0.98         0.94         0.84        97.28
2          0.03         0.03         0.03         0.48
3          0.00         0.00         0.00         0.00
4          0.88         0.82          NaN         0.74
5          0.28         0.27          NaN         0.23
6          0.92         0.84         1.52         1.36
7          0.40         0.40          NaN         0.50
8          0.38         0.32         0.32         0.32
9          4.48         3.56         3.26         2.80
10         0.03         0.05          NaN          NaN
11         0.04         0.04          NaN         0.02
12         0.00         0.00         0.00         0.00
13         0.60         0.83         0.90         0.87
14         0.00         0.00          NaN          NaN
15         0.00         0.00          NaN          NaN
16          NaN          NaN          NaN          NaN
17         0.06         0.60         0.06          NaN
18         0.48         0.45          NaN         0.34
19         2.80         2.80         2.56         2.24

[20 rows x 304 columns]

In [135]:
data.iloc[:, 3] #first column of dates for the ROE, last is at 27
data.iloc[:, 28] #first ROE, .last is at 52

0      17.4%
1      19.0%
2      54.1%
3       9.6%
4      17.7%
       ...
310     7.3%
311    25.2%
312    20.6%
313      NaN
314      NaN
Name: Unnamed: 28, Length: 315, dtype: object

In [137]:
# Select company-related columns (Company Name and ISIN Code)
company_info_columns = ['Company Name', 'ISIN Code']
company_info = data[company_info_columns]

# Convert all ROE date columns (3 to 27) to datetime and extract years
for i in range(3, 28):
    data[f'Year_{i}'] = pd.to_datetime(data.iloc[:, i], format='%d/%m/%Y', errors='coerce').dt.year

# Initialize an empty DataFrame to store ROE per year
roe_per_year = pd.DataFrame(index=data.index)

# Loop through each row to correctly place ROE ratios in the right year columns
for index, row in data.iterrows():
    for i in range(3, 28):  # Date columns for ROE
        year = row[f'Year_{i}']  # Extract the year
        roe_column = data.columns[i + 25]  # ROE column (offset by 25)
        
        if pd.notna(year):  # If the year is valid
            roe_per_year.at[index, f"ROE_{int(year)}"] = row[roe_column]

# Sort columns from most recent year to oldest
roe_per_year = roe_per_year[sorted(roe_per_year.columns, key=lambda x: int(x.split('_')[-1]), reverse=True)]

# Concatenate company info with sorted ROE ratios
USA_finance = pd.concat([company_info, roe_per_year], axis=1)

# Display the resulting DataFrame
print(USA_finance)

                       Company Name     ISIN Code ROE_2025 ROE_2024 ROE_2023  \
0                         Aflac Inc  US0010551028    17.4%    16.8%    13.0%
1               Abbott Laboratories  US0028241000    19.0%    20.7%    26.1%
2                         Adobe Inc  US00724F1012      NaN    54.1%    48.3%
3        Advanced Micro Devices Inc  US0079031078     9.6%     7.8%    17.7%
4    Air Products and Chemicals Inc  US0091581068      NaN    17.7%    18.3%
..                              ...           ...      ...      ...      ...
310                     Corteva Inc  US22052L1044     7.3%     7.6%     7.6%
311                       Amcor PLC  JE00BJ1F3079      NaN    25.2%    26.6%
312             Carrier Global Corp  US14448C1045    20.6%    28.3%    27.8%
313             Otis Worldwide Corp  US68902V1070      NaN   -30.2%   -20.1%
314            Smurfit WestRock PLC  IE00028FXN24      NaN      NaN      NaN

    ROE_2022 ROE_2021 ROE_2020 ROE_2019 ROE_2018  ...   ROE_2009 ROE_2008  \
0      12.0%    11.4%    12.6%    13.4%    12.1%  ...      28.8%    18.3%
1      27.3%    20.5%    18.9%    16.7%    17.1%  ...      29.7%    24.9%
2      44.8%    42.8%    41.2%    38.9%    30.9%  ...      16.8%    25.8%
3      51.5%    36.4%    36.9%    54.8%    34.9%  ...  -1,371.3%   -45.9%
4      16.6%    15.7%    15.4%    16.6%    15.7%  ...      17.6%    21.1%
..       ...      ...      ...      ...      ...  ...        ...      ...
310     6.3%     4.6%     2.2%      NaN      NaN  ...        NaN      NaN
311    27.7%    24.4%    20.0%      NaN      NaN  ...        NaN      NaN
312    30.9%    14.4%      NaN      NaN      NaN  ...        NaN      NaN
313   -34.7%  -102.8%      NaN      NaN      NaN  ...        NaN      NaN
314      NaN      NaN      NaN      NaN      NaN  ...        NaN      NaN

    ROE_2007 ROE_2006 ROE_2005 ROE_2004 ROE_2003 ROE_2002 ROE_2001 ROE_2000
0      17.2%      NaN      NaN      NaN      NaN      NaN      NaN      NaN
1      26.6%      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2      20.8%    14.6%    30.8%    31.5%    24.2%    34.4%      NaN      NaN
3       6.7%     8.2%     4.7%   -11.3%   -27.7%      NaN      NaN      NaN
4      17.8%    16.4%    15.6%      NaN      NaN      NaN      NaN      NaN
..       ...      ...      ...      ...      ...      ...      ...      ...
310      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
311      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
312      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
313      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
314      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

[315 rows x 28 columns]

C:\Users\fbergsma1\AppData\Local\Temp\ipykernel_21664\1830657118.py:19: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '14.6%' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  roe_per_year.at[index, f"ROE_{int(year)}"] = row[roe_column]
C:\Users\fbergsma1\AppData\Local\Temp\ipykernel_21664\1830657118.py:19: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '30.8%' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  roe_per_year.at[index, f"ROE_{int(year)}"] = row[roe_column]
C:\Users\fbergsma1\AppData\Local\Temp\ipykernel_21664\1830657118.py:19: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '31.5%' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  roe_per_year.at[index, f"ROE_{int(year)}"] = row[roe_column]
C:\Users\fbergsma1\AppData\Local\Temp\ipykernel_21664\1830657118.py:19: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '24.2%' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  roe_per_year.at[index, f"ROE_{int(year)}"] = row[roe_column]
C:\Users\fbergsma1\AppData\Local\Temp\ipykernel_21664\1830657118.py:19: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '34.4%' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  roe_per_year.at[index, f"ROE_{int(year)}"] = row[roe_column]
C:\Users\fbergsma1\AppData\Local\Temp\ipykernel_21664\1830657118.py:19: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '18.8%' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  roe_per_year.at[index, f"ROE_{int(year)}"] = row[roe_column]

In [151]:
data.iloc[:, 53] #first column of dates for the ROA, last is at 77
data.iloc[:, 78] #first ROA, .last is at 102

0       3.4%
1      10.6%
2      27.6%
3       7.9%
4       7.7%
       ...
310     4.3%
311     6.0%
312     6.7%
313    14.4%
314      NaN
Name: Unnamed: 78, Length: 315, dtype: object

In [155]:
# Convert all ROA date columns (53 to 77) to datetime and extract years
for i in range(53, 78):
    data[f'Year_ROA_{i}'] = pd.to_datetime(data.iloc[:, i], format='%d/%m/%Y', errors='coerce').dt.year

# Initialize an empty DataFrame to store ROA per year
roa_per_year = pd.DataFrame(index=data.index)

# Loop through each row to correctly place ROA ratios in the right year columns
for index, row in data.iterrows():
    for i in range(53, 78):  # Date columns for ROA
        year = row[f'Year_ROA_{i}']  # Extract the year
        roa_column = data.columns[i + 25]  # ROA column (offset by 25)
        
        if pd.notna(year):  # If the year is valid
            roa_per_year.at[index, f"ROA_{int(year)}"] = row[roa_column]

# Sort columns from most recent year to oldest for ROA
roa_per_year = roa_per_year[sorted(roa_per_year.columns, key=lambda x: int(x.split('_')[-1]), reverse=True)]

# Concatenate company info with sorted ROE and ROA ratios
USA_finance = pd.concat([company_info, roe_per_year, roa_per_year], axis=1)

# Display the resulting DataFrame
print(USA_finance)

                       Company Name     ISIN Code ROE_2025 ROE_2024 ROE_2023  \
0                         Aflac Inc  US0010551028    17.4%    16.8%    13.0%
1               Abbott Laboratories  US0028241000    19.0%    20.7%    26.1%
2                         Adobe Inc  US00724F1012      NaN    54.1%    48.3%
3        Advanced Micro Devices Inc  US0079031078     9.6%     7.8%    17.7%
4    Air Products and Chemicals Inc  US0091581068      NaN    17.7%    18.3%
..                              ...           ...      ...      ...      ...
310                     Corteva Inc  US22052L1044     7.3%     7.6%     7.6%
311                       Amcor PLC  JE00BJ1F3079      NaN    25.2%    26.6%
312             Carrier Global Corp  US14448C1045    20.6%    28.3%    27.8%
313             Otis Worldwide Corp  US68902V1070      NaN   -30.2%   -20.1%
314            Smurfit WestRock PLC  IE00028FXN24      NaN      NaN      NaN

    ROE_2022 ROE_2021 ROE_2020 ROE_2019 ROE_2018  ... ROA_2009 ROA_2008  \
0      12.0%    11.4%    12.6%    13.4%    12.1%  ...     2.4%     2.5%
1      27.3%    20.5%    18.9%    16.7%    17.1%  ...    12.2%    11.2%
2      44.8%    42.8%    41.2%    38.9%    30.9%  ...    11.2%    19.5%
3      51.5%    36.4%    36.9%    54.8%    34.9%  ...   -15.5%   -11.9%
4      16.6%    15.7%    15.4%    16.6%    15.7%  ...      NaN     8.7%
..       ...      ...      ...      ...      ...  ...      ...      ...
310     6.3%     4.6%     2.2%      NaN      NaN  ...      NaN      NaN
311    27.7%    24.4%    20.0%      NaN      NaN  ...      NaN      NaN
312    30.9%    14.4%      NaN      NaN      NaN  ...      NaN      NaN
313   -34.7%  -102.8%      NaN      NaN      NaN  ...      NaN      NaN
314      NaN      NaN      NaN      NaN      NaN  ...      NaN      NaN

    ROA_2007 ROA_2006 ROA_2005 ROA_2004 ROA_2003 ROA_2002 ROA_2001 ROA_2000
0       2.4%      NaN      NaN      NaN      NaN      NaN      NaN      NaN
1      10.7%      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2      16.9%    12.6%    23.5%    22.9%    17.1%      NaN      NaN      NaN
3       3.0%     3.8%     1.8%    -3.9%      NaN      NaN      NaN      NaN
4       7.7%     7.2%     6.9%      NaN      NaN      NaN      NaN      NaN
..       ...      ...      ...      ...      ...      ...      ...      ...
310      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
311      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
312      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
313      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
314      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

[315 rows x 54 columns]

C:\Users\fbergsma1\AppData\Local\Temp\ipykernel_21664\121265719.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '6.8%' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  roa_per_year.at[index, f"ROA_{int(year)}"] = row[roa_column]
C:\Users\fbergsma1\AppData\Local\Temp\ipykernel_21664\121265719.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '12.2%' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  roa_per_year.at[index, f"ROA_{int(year)}"] = row[roa_column]
C:\Users\fbergsma1\AppData\Local\Temp\ipykernel_21664\121265719.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '12.2%' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  roa_per_year.at[index, f"ROA_{int(year)}"] = row[roa_column]
C:\Users\fbergsma1\AppData\Local\Temp\ipykernel_21664\121265719.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '12.6%' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  roa_per_year.at[index, f"ROA_{int(year)}"] = row[roa_column]
C:\Users\fbergsma1\AppData\Local\Temp\ipykernel_21664\121265719.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '23.5%' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  roa_per_year.at[index, f"ROA_{int(year)}"] = row[roa_column]
C:\Users\fbergsma1\AppData\Local\Temp\ipykernel_21664\121265719.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '22.9%' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  roa_per_year.at[index, f"ROA_{int(year)}"] = row[roa_column]
C:\Users\fbergsma1\AppData\Local\Temp\ipykernel_21664\121265719.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '17.1%' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  roa_per_year.at[index, f"ROA_{int(year)}"] = row[roa_column]
C:\Users\fbergsma1\AppData\Local\Temp\ipykernel_21664\121265719.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2.9%' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  roa_per_year.at[index, f"ROA_{int(year)}"] = row[roa_column]
C:\Users\fbergsma1\AppData\Local\Temp\ipykernel_21664\121265719.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.0%' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  roa_per_year.at[index, f"ROA_{int(year)}"] = row[roa_column]

In [171]:
data.iloc[:, 103] #first column of dates for the EPS, last is at 127
data.iloc[:, 128] #first EPS, .last is at 152

0       7.39
1       4.67
2      18.42
3       3.31
4      12.43
       ...
310     2.57
311     0.70
312     2.56
313     3.83
314     2.42
Name: Unnamed: 128, Length: 315, dtype: object

In [173]:
# Convert all EPS date columns (103 to 127) to datetime and extract years
for i in range(103, 128):
    data[f'Year_EPS_{i}'] = pd.to_datetime(data.iloc[:, i], format='%d/%m/%Y', errors='coerce').dt.year

# Initialize an empty DataFrame to store EPS per year
eps_per_year = pd.DataFrame(index=data.index)

# Loop through each row to correctly place EPS ratios in the right year columns
for index, row in data.iterrows():
    for i in range(103, 128):  # Date columns for EPS
        year = row[f'Year_EPS_{i}']  # Extract the year
        eps_column = data.columns[i + 25]  # EPS column (offset by 25)
        
        if pd.notna(year):  # If the year is valid
            eps_per_year.at[index, f"EPS_{int(year)}"] = row[eps_column]

# Sort columns from most recent year to oldest for EPS
eps_per_year = eps_per_year[sorted(eps_per_year.columns, key=lambda x: int(x.split('_')[-1]), reverse=True)]

# Concatenate company info with sorted ROE, ROA, and EPS ratios
USA_finance = pd.concat([company_info, roe_per_year, roa_per_year, eps_per_year], axis=1)

# Display the resulting DataFrame
print(USA_finance)

                       Company Name     ISIN Code ROE_2025 ROE_2024 ROE_2023  \
0                         Aflac Inc  US0010551028    17.4%    16.8%    13.0%
1               Abbott Laboratories  US0028241000    19.0%    20.7%    26.1%
2                         Adobe Inc  US00724F1012      NaN    54.1%    48.3%
3        Advanced Micro Devices Inc  US0079031078     9.6%     7.8%    17.7%
4    Air Products and Chemicals Inc  US0091581068      NaN    17.7%    18.3%
..                              ...           ...      ...      ...      ...
310                     Corteva Inc  US22052L1044     7.3%     7.6%     7.6%
311                       Amcor PLC  JE00BJ1F3079      NaN    25.2%    26.6%
312             Carrier Global Corp  US14448C1045    20.6%    28.3%    27.8%
313             Otis Worldwide Corp  US68902V1070      NaN   -30.2%   -20.1%
314            Smurfit WestRock PLC  IE00028FXN24      NaN      NaN      NaN

    ROE_2022 ROE_2021 ROE_2020 ROE_2019 ROE_2018  ... EPS_2009 EPS_2008  \
0      12.0%    11.4%    12.6%    13.4%    12.1%  ...     2.00     1.64
1      27.3%    20.5%    18.9%    16.7%    17.1%  ...     3.32     2.84
2      44.8%    42.8%    41.2%    38.9%    30.9%  ...     1.54     2.07
3      51.5%    36.4%    36.9%    54.8%    34.9%  ...    -1.67    -2.46
4      16.6%    15.7%    15.4%    16.6%    15.7%  ...     4.06     4.97
..       ...      ...      ...      ...      ...  ...      ...      ...
310     6.3%     4.6%     2.2%      NaN      NaN  ...      NaN      NaN
311    27.7%    24.4%    20.0%      NaN      NaN  ...      NaN      NaN
312    30.9%    14.4%      NaN      NaN      NaN  ...      NaN      NaN
313   -34.7%  -102.8%      NaN      NaN      NaN  ...      NaN      NaN
314      NaN      NaN      NaN      NaN      NaN  ...      NaN      NaN

    EPS_2007 EPS_2006 EPS_2005 EPS_2004 EPS_2003 EPS_2002 EPS_2001 EPS_2000
0       1.43     1.27     1.15     0.95     0.78     0.67     0.60      NaN
1       2.53     2.50     2.27     2.21     2.06     1.88     1.78      NaN
2       1.61     1.23     1.13     0.91     0.57     0.48     0.58     0.56
3       0.79     0.62     0.38    -0.79    -2.00     0.09     2.35      NaN
4       4.38     3.55     3.08     2.64     2.22     2.33     2.42     2.46
..       ...      ...      ...      ...      ...      ...      ...      ...
310      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
311      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
312      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
313      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
314      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

[315 rows x 80 columns]

In [175]:
# Export to Excel
USA_finance.to_excel('USA_finance.xlsx', index=False, engine='openpyxl')

# Control Variables

In [36]:
USA_data.iloc[:, 406] #first column of dates for the Market Capitalization, last is at 430
USA_data.iloc[:, 431] #first market capitalization, .last is at 455

0       56,888,276,160.00
1      196,184,229,142.43
2      227,525,130,000.00
3      203,159,251,645.74
4       66,191,919,825.48
              ...
310     39,051,491,200.00
311     14,135,456,613.36
312     61,244,739,661.86
313     36,994,039,127.64
314     28,015,608,192.32
Name: Unnamed: 432, Length: 315, dtype: object

In [38]:
print(USA_data.head())

  Identifier                    Company Name     ISIN Code Ticker Symbol  \
0      AFL.N                       Aflac Inc  US0010551028           AFL
1      ABT.N             Abbott Laboratories  US0028241000           ABT
2    ADBE.OQ                       Adobe Inc  US00724F1012          ADBE
3     AMD.OQ      Advanced Micro Devices Inc  US0079031078           AMD
4      APD.N  Air Products and Chemicals Inc  US0091581068           APD

        Country of Exchange  \
0  United States of America
1  United States of America
2  United States of America
3  United States of America
4  United States of America

                        NAICS National Industry Name  \
0       Direct Health and Medical Insurance Carriers
1  Electromedical and Electrotherapeutic Apparatu...
2                                Software Publishers
3     Semiconductor and Related Device Manufacturing
4                       Industrial Gas Manufacturing

  ESG Score\nIn the last 25 FY  Unnamed: 8  Unnamed: 9 Unnamed: 10  ...  \
0                   31/12/2023  31/12/2022  31/12/2021  31/12/2020  ...
1                   31/12/2023  31/12/2022  31/12/2021  31/12/2020  ...
2                   01/12/2023  02/12/2022  03/12/2021  27/11/2020  ...
3                   30/12/2023  31/12/2022  25/12/2021  26/12/2020  ...
4                   30/09/2023  30/09/2022  30/09/2021  30/09/2020  ...

  Unnamed: 1622 Unnamed: 1623 Unnamed: 1624 Unnamed: 1625 Unnamed: 1626  \
0  1,211,600.00  2,132,000.00  1,436,000.00          0.00          0.00
1  1,408,500.00  1,644,600.00  2,511,500.00          0.00          0.00
2    885,600.00  1,916,445.00  1,829,932.00          0.00          0.00
3  1,390,100.00  2,939,100.00  5,420,900.00          0.00          0.00
4    184,900.00    709,600.00    628,800.00          0.00          0.00

  Unnamed: 1627 Unnamed: 1628 Unnamed: 1629 Unnamed: 1630 Unnamed: 1631
0  1,176,000.00  2,067,800.00  2,255,800.00  3,150,800.00          0.00
1  1,656,900.00  2,893,300.00  7,178,000.00  1,674,000.00          0.00
2  2,380,440.00  2,226,304.00  4,054,600.00  3,779,000.00          0.00
3  2,665,300.00  4,209,800.00  2,742,200.00  2,135,600.00          0.00
4    301,800.00    535,300.00    486,100.00    844,200.00          0.00

[5 rows x 1631 columns]

In [40]:
# Define a function to process market capitalization scores for USA_data
def process_market_cap_usa(USA_data, date_columns_range, market_cap_columns_offset):
    # Convert date columns to datetime and extract years
    for i in range(date_columns_range[0], date_columns_range[1] + 1):
        USA_data[f'Year_MarketCap_{i}'] = pd.to_datetime(USA_data.iloc[:, i], format='%d/%m/%Y', errors='coerce').dt.year

    # Create an empty DataFrame for market capitalization values
    market_cap_per_year = pd.DataFrame(index=USA_data.index)

    # Loop through each row to place market capitalization values in the corresponding year columns
    for index, row in USA_data.iterrows():
        for i in range(date_columns_range[0], date_columns_range[1] + 1):  # Date columns
            year = row[f'Year_MarketCap_{i}']  # Extract the year
            market_cap_column = USA_data.columns[i + market_cap_columns_offset]  # Market capitalization column (offset by 25)

            if pd.notna(year):  # If the year is valid
                market_cap_per_year.at[index, f"MarketCap_{int(year)}"] = row[market_cap_column]  # Ensure the year is an integer

    # Sort columns from most recent year to oldest
    market_cap_per_year = market_cap_per_year[sorted(market_cap_per_year.columns, key=lambda x: int(x.split('_')[-1]), reverse=True)]

    return market_cap_per_year

# Select company-related columns for USA_data
company_info_columns_usa = ['Company Name', 'ISIN Code', 'Ticker Symbol', 'Country of Exchange', 'NAICS National Industry Name']
company_info_usa = USA_data[company_info_columns_usa]

# Initialize an empty DataFrame for the final result
USA_control_variables = pd.DataFrame()

# Process Market Capitalization data and get values per year
market_cap_per_year_usa = process_market_cap_usa(USA_data, (406, 430), 25)

# Concatenate company info with the processed market capitalization data
USA_control_variables = pd.concat([company_info_usa, market_cap_per_year_usa], axis=1)

# Display the resulting DataFrame
print(USA_control_variables)

                       Company Name     ISIN Code Ticker Symbol  \
0                         Aflac Inc  US0010551028           AFL
1               Abbott Laboratories  US0028241000           ABT
2                         Adobe Inc  US00724F1012          ADBE
3        Advanced Micro Devices Inc  US0079031078           AMD
4    Air Products and Chemicals Inc  US0091581068           APD
..                              ...           ...           ...
310                     Corteva Inc  US22052L1044          CTVA
311                       Amcor PLC  JE00BJ1F3079          AMCR
312             Carrier Global Corp  US14448C1045          CARR
313             Otis Worldwide Corp  US68902V1070          OTIS
314            Smurfit WestRock PLC  IE00028FXN24            SW

          Country of Exchange  \
0    United States of America
1    United States of America
2    United States of America
3    United States of America
4    United States of America
..                        ...
310  United States of America
311  United States of America
312  United States of America
313  United States of America
314  United States of America

                          NAICS National Industry Name MarketCap_2025  \
0         Direct Health and Medical Insurance Carriers            NaN
1    Electromedical and Electrotherapeutic Apparatu...            NaN
2                                  Software Publishers            NaN
3       Semiconductor and Related Device Manufacturing            NaN
4                         Industrial Gas Manufacturing            NaN
..                                                 ...            ...
310                 Farm Supplies Merchant Wholesalers            NaN
311  Plastics Packaging Film and Sheet (including L...            NaN
312  Air-Conditioning and Warm Air Heating Equipmen...            NaN
313         Elevator and Moving Stairway Manufacturing            NaN
314                All Other Business Support Services            NaN

         MarketCap_2024      MarketCap_2023      MarketCap_2022  \
0     56,888,276,160.00   49,010,154,435.00   44,731,469,006.40
1    196,184,229,142.43  191,087,963,057.52  191,426,964,976.83
2    227,525,130,000.00  278,857,591,000.00  158,777,297,000.00
3    203,159,251,645.74  238,140,691,522.31  104,512,926,420.84
4     66,191,919,825.48   62,956,958,867.40   51,619,277,080.86
..                  ...                 ...                 ...
310   39,051,491,200.00   34,011,890,880.00   41,997,839,760.00
311   14,135,456,613.36   14,685,009,133.98   18,679,390,118.29
312   61,244,739,661.86   48,203,225,963.55   34,495,787,493.75
313   36,994,039,127.64   36,616,386,893.81   32,622,855,689.87
314   28,015,608,192.32   10,625,060,697.02    9,670,752,370.68

         MarketCap_2021  ...     MarketCap_2009     MarketCap_2008  \
0     38,626,632,707.41  ...  21,640,339,711.25  21,389,631,600.00
1    248,868,708,017.06  ...  83,508,407,619.74  82,807,940,733.12
2    293,344,974,000.00  ...  18,530,632,974.84  12,296,942,928.60
3    176,480,191,893.70  ...   6,642,669,263.93   1,326,501,544.46
4     56,693,703,072.60  ...  16,298,137,199.88  14,508,785,921.31
..                  ...  ...                ...                ...
310   34,462,817,520.00  ...                NaN                NaN
311   17,668,947,184.08  ...   3,391,811,259.84   4,065,669,686.99
312   46,811,240,621.28  ...                NaN                NaN
313   36,984,633,782.55  ...                NaN                NaN
314   13,923,064,546.25  ...   1,935,165,245.38     553,125,300.33

        MarketCap_2007     MarketCap_2006     MarketCap_2005  \
0    30,551,843,554.46  22,747,181,056.00  23,227,105,816.42
1    86,767,051,829.55  74,763,216,769.62  61,164,933,327.91
2    24,179,423,454.48  22,954,580,104.00  17,279,641,262.78
3     4,432,163,646.84  11,164,135,132.15  12,324,094,984.00
4    21,125,743,119.52  14,623,869,430.76  12,224,293,784.94
..                 ...                ...                ...
310                NaN                NaN                NaN
311   5,612,618,036.74   4,365,059,071.45   4,484,849,948.54
312                NaN                NaN                NaN
313                NaN                NaN                NaN
314   3,559,584,567.85                NaN                NaN

        MarketCap_2004     MarketCap_2003     MarketCap_2002  \
0    20,158,400,488.32  18,554,187,265.38  15,547,302,564.48
1    72,652,350,934.95  72,852,262,987.80  62,501,625,000.00
2    15,023,957,682.88   9,667,046,625.84   6,977,122,790.80
3     8,119,548,650.36   5,124,282,907.80   2,181,060,027.00
4    12,360,132,271.26  10,249,600,537.00   9,545,486,489.88
..                 ...                ...                ...
310                NaN                NaN                NaN
311   4,272,228,206.05   4,636,010,255.38   3,587,922,380.10
312                NaN                NaN                NaN
313                NaN                NaN                NaN
314                NaN                NaN                NaN

        MarketCap_2001     MarketCap_2000
0    12,824,536,116.96  19,146,502,495.31
1    86,550,516,484.00  74,921,332,860.94
2     7,609,105,822.24  16,178,065,974.38
3     5,566,370,109.30   4,329,002,407.44
4     8,770,211,617.20   8,254,986,876.00
..                 ...                ...
310                NaN                NaN
311   2,141,491,638.39   2,173,745,325.72
312                NaN                NaN
313                NaN                NaN
314                NaN                NaN

[315 rows x 31 columns]

In [42]:
# Export to Excel
USA_control_variables.to_excel('USA_control_variables.xlsx', index=False, engine='openpyxl')